# Generated by Django 6.0.3 on 2026-04-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_habito_meta_fecha_completada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='fecha_completado',
        ),
        migrations.AddField(
            model_name='meta',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
